twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        config: '@App\Service\Config'
        news: '@App\Service\News'
        menu: '@App\Service\Menu'
