admin_login:
    path: /login
    controller: App\Controller\SecurityController::adminLogin
admin_logout:
    path: /logout
admin:
    path: /
    controller: App\Controller\Admin\DefaultController::index

admin_user:
    resource: "admin/user.yml"
    prefix: /user

admin_admin:
    resource: "admin/admin.yml"
    prefix: /admin

admin_article:
    resource: "admin/article.yml"
    prefix: /article

admin_category:
    resource: "admin/category.yml"
    prefix: /category

admin_config:
    resource: "admin/config.yml"
    prefix: /config

admin_contact:
    resource: "admin/contacts.yml"
    prefix: /contacts

admin_offer:
    resource: "admin/offer.yml"
    prefix: /offer

admin_offer_statuses:
    resource: "admin/offer_status.yml"
    prefix: /offer_status

admin_comment:
    resource: "admin/comments.yml"
    prefix: /comments
