index:
    path: /
    controller: App\Controller\DefaultController::startPage
contact:
    path: /contact
    controller: App\Controller\DefaultController::contactPage
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
register:
    path: /register
    controller: App\Controller\UserController::register
enable_user:
    path: /enable_user/{h}
    controller: App\Controller\UserController::enable
enable_subscriber:
    path: /enable_subscriber/{h}
    controller: App\Controller\SubscriberController::enable

front_article:
    resource: "front/article.yml"
    prefix: /article

front_user:
    resource: "front/user.yml"
    prefix: /user

front_offer:
    resource: "front/offer.yml"
    prefix: /offer

front_realization:
    resource: "front/realization.yml"
    prefix: /realization

front_about_us:
    resource: "front/about_us.yml"
    prefix: /about_us

front_news:
    resource: "front/news.yml"
    prefix: /news

front_sublease_zone:
    resource: "front/sublease_zone.yml"
    prefix: /sublease_zone

front_investor_zone:
    resource: "front/investor_zone.yml"
    prefix: /investor_zone

front_subscribe:
    resource: "front/subscriber.yml"
    prefix: /subscriber
