index:
    path: /
    controller: App\Controller\FrontController::startPage
contact:
    path: /contact
    controller: App\Controller\FrontController::contactPage
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
register:
    path: /register
    controller: App\Controller\UserController::register

front_article:
    resource: "front/article.yml"
    prefix: /article

front_user:
    resource: "front/user.yml"
    prefix: /user
