index:
    path: /
    controller: App\Controller\DefaultController::startPage
index_start:
    path: /index
    controller: App\Controller\DefaultController::startPage
contact:
    path: /contact
    controller: App\Controller\DefaultController::contactPage
login:
    path: /login
    controller: App\Controller\SecurityController::login
    schemes: [https]
logout:
    path: /logout
register:
    path: /register
    controller: App\Controller\UserController::register
    schemes: [https]
enable_user:
    path: /enable_user/{h}
    controller: App\Controller\UserController::enable
enable_subscriber:
    path: /enable_subscriber/{h}
    controller: App\Controller\SubscriberController::enable

front_article_resource:
    resource: "front/article.yml"
    prefix: /article

front_user_resource:
    resource: "front/user.yml"
    prefix: /user
    schemes: [https]

front_offer_resource:
    resource: "front/offer.yml"
    prefix: /offer

front_realization_resource:
    resource: "front/realization.yml"
    prefix: /realization
front_realizations:
    path: /realization
    controller: App\Controller\RealizationController::index

front_news_resource:
    resource: "front/news.yml"
    prefix: /news
front_news:
    path: /news
    controller: App\Controller\NewsController::index

front_investor_zone_resource:
    resource: "front/investor_zone.yml"
    prefix: /investor_zone
front_investor_zone:
    path: /investor_zone
    controller: App\Controller\InvestorZoneController::index

front_subscribe:
    resource: "front/subscriber.yml"
    prefix: /subscriber

front_menu_resource:
    resource: "front/menu.yml"
