index:
    path: /
    controller: App\Controller\DefaultController::startPage
contact:
    path: /contact
    controller: App\Controller\DefaultController::contactPage
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
register:
    path: /register
    controller: App\Controller\UserController::register

front_article:
    resource: "front/article.yml"
    prefix: /article

front_user:
    resource: "front/user.yml"
    prefix: /user

front_offer:
    resource: "front/offer.yml"
    prefix: /offer

front_realization:
    resource: "front/realization.yml"
    prefix: /realization
