front_user_register:
    path: /register
    controller: App\Controller\UserController::register
front_user_account:
    path: /account
    controller: App\Controller\UserController::account
front_user_account_edit:
    path: /account/edit
    controller: App\Controller\UserController::edit

front_user_recruitment_user_new:
    path: /recruitment_user/{recruitmentId}/new
    controller: App\Controller\RecruitmentUserController::new
