index:
    path: /
    controller: App\Controller\FrontController::startPage
contact:
    path: /contact
    controller: App\Controller\FrontController::contactPage
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
admin_login:
    path: /admin/login
    controller: App\Controller\SecurityController::adminLogin
administrator:
    path: /administrator
    controller: App\Controller\SecurityController::adminLogin
admin_logout:
    path: /admin/logout
admin:
    path: /admin
    controller: App\Controller\AdminController::startPage
admin_start:
    path: /admin/start
    controller: App\Controller\AdminController::startPage
admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::users
