parameters:
    locale: pl
    public_dir: 'public_html'
    file_directory: '../%public_dir%/uploads/files'
    image_directory: 'uploads/files'
    number_of_latest_news: 3

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\FileUploader:
        arguments:
            $targetDir: '%file_directory%'
            $imageDir: '%image_directory%'

    App\EventListener\ImageUploadListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\Service\Config:
        arguments: ['@doctrine.orm.entity_manager']

    App\Service\News:
        arguments: ['@doctrine.orm.entity_manager']

    App\Service\Menu:
        arguments: ['@doctrine.orm.entity_manager']

artgris_file_manager:
    web_dir: "%public_dir%"
    conf:
        default:
            dir: "%file_directory%"
