admin_articles:
    path: /
    controller: App\Controller\AdminController::articles

admin_article_new:
    path: /new
    controller: App\Controller\AdminController::articleNew

admin_article_show:
    path: /{id}
    controller: App\Controller\AdminController::articleShow

admin_article_edit:
    path: /edit/{id}
    controller: App\Controller\AdminController::articleEdit

admin_article_disable:
    path: /disable/{id}/{status}
    controller: App\Controller\AdminController::articleDisable

admin_article_delete:
    path: /delete/{id}
    controller: App\Controller\AdminController::articleDelete
