admin_categories:
    path: /
    controller: App\Controller\AdminController::categories

admin_category_new:
    path: /new
    controller: App\Controller\AdminController::categoryNew

admin_category_show:
    path: /{id}
    controller: App\Controller\AdminController::categoryShow

admin_category_edit:
    path: /edit/{id}
    controller: App\Controller\AdminController::categoryEdit

admin_category_disable:
    path: /disable/{id}/{status}
    controller: App\Controller\AdminController::categoryDisable

admin_category_delete:
    path: /delete/{id}
    controller: App\Controller\AdminController::categoryDelete
