admin_categories:
    path: /
    controller: App\Controller\Admin\CategoryController::categories

admin_category_new:
    path: /new
    controller: App\Controller\Admin\CategoryController::new

admin_category_show:
    path: /{id}
    controller: App\Controller\Admin\CategoryController::show

admin_category_edit:
    path: /edit/{id}
    controller: App\Controller\Admin\CategoryController::edit

admin_category_disable:
    path: /disable/{id}/{status}
    controller: App\Controller\Admin\CategoryController::disable

admin_category_delete:
    path: /delete/{id}
    controller: App\Controller\Admin\CategoryController::delete
