admin_users:
    path: /
    controller: App\Controller\Admin\UserController::users

admin_user_new:
    path: /new
    controller: App\Controller\Admin\UserController::new

admin_user_edit:
    path: /edit/{id}
    controller: App\Controller\Admin\UserController::edit

admin_user_show:
    path: /show/{id}
    controller: App\Controller\Admin\UserController::show

admin_user_disable:
    path: /disable/{id}/{status}
    controller: App\Controller\Admin\UserController::disable

admin_user_delete:
    path: /delete/{id}
    controller: App\Controller\Admin\UserController::delete

admin_user_disable_by_admin:
    path: /disable-by-admin/{id}/{status}
    controller: App\Controller\Admin\UserController::disableByAdmin
