admin_users:
    path: /
    controller: App\Controller\AdminController::users

admin_user_new:
    path: /new
    controller: App\Controller\AdminController::userNew

admin_user_edit:
    path: /edit/{id}
    controller: App\Controller\AdminController::userEdit

admin_user_disable:
    path: /disable/{id}/{status}
    controller: App\Controller\AdminController::userDisable

admin_user_delete:
    path: /delete/{id}
    controller: App\Controller\AdminController::userDelete
